package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	generateMarker     = "generate:reset"
	generatedFileName  = "reset.gen.go"
	generatedFileIntro = "// Code generated by reset generator. DO NOT EDIT."
)

type packageContext struct {
	Dir         string
	Name        string
	Files       []*ast.File
	TypeByName  map[string]ast.Expr
	MarkedTypes []markedStruct
}

type markedStruct struct {
	Name   string
	Struct *ast.StructType
}

func main() {
	flag.Parse()

	root := "."
	if flag.NArg() > 1 {
		_, _ = fmt.Fprintln(os.Stderr, "usage: reset [root]")
		os.Exit(2)
	}
	if flag.NArg() == 1 {
		root = flag.Arg(0)
	}

	if err := run(root); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string) error {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return fmt.Errorf("resolve root: %w", err)
	}

	pkgs, err := scanPackages(absRoot)
	if err != nil {
		return err
	}

	var generated int
	for _, pkg := range pkgs {
		if len(pkg.MarkedTypes) == 0 {
			continue
		}

		content, err := generateFile(pkg)
		if err != nil {
			return fmt.Errorf("generate %s: %w", pkg.Dir, err)
		}

		formatted, err := format.Source(content)
		if err != nil {
			return fmt.Errorf("gofmt %s: %w", pkg.Dir, err)
		}

		path := filepath.Join(pkg.Dir, generatedFileName)
		if err := writeFileIfChanged(path, formatted); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		generated++
	}

	_, _ = fmt.Fprintf(os.Stdout, "generated reset methods for %d package(s)\n", generated)
	return nil
}

func scanPackages(root string) ([]packageContext, error) {
	ctxByDirAndPkg := make(map[string]*packageContext)
	fset := token.NewFileSet()

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if d.IsDir() {
			name := d.Name()
			if strings.HasPrefix(name, ".") && path != root {
				return filepath.SkipDir
			}
			if name == "vendor" || name == "bin" {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		if filepath.Base(path) == generatedFileName {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		dir := filepath.Dir(path)
		key := dir + "::" + file.Name.Name
		ctx, ok := ctxByDirAndPkg[key]
		if !ok {
			ctx = &packageContext{
				Dir:        dir,
				Name:       file.Name.Name,
				TypeByName: make(map[string]ast.Expr),
			}
			ctxByDirAndPkg[key] = ctx
		}
		ctx.Files = append(ctx.Files, file)
		return nil
	})
	if err != nil {
		return nil, err
	}

	if len(ctxByDirAndPkg) == 0 {
		return nil, errors.New("no packages found")
	}

	pkgs := make([]packageContext, 0, len(ctxByDirAndPkg))
	for _, ctx := range ctxByDirAndPkg {
		collectTypes(ctx)
		pkgs = append(pkgs, *ctx)
	}

	sort.Slice(pkgs, func(i, j int) bool {
		if pkgs[i].Dir == pkgs[j].Dir {
			return pkgs[i].Name < pkgs[j].Name
		}
		return pkgs[i].Dir < pkgs[j].Dir
	})

	return pkgs, nil
}

func collectTypes(ctx *packageContext) {
	for _, file := range ctx.Files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				ctx.TypeByName[ts.Name.Name] = ts.Type

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if hasGenerateResetMarker(gen, ts) {
					ctx.MarkedTypes = append(ctx.MarkedTypes, markedStruct{Name: ts.Name.Name, Struct: st})
				}
			}
		}
	}

	sort.Slice(ctx.MarkedTypes, func(i, j int) bool {
		return ctx.MarkedTypes[i].Name < ctx.MarkedTypes[j].Name
	})
}

func hasGenerateResetMarker(gen *ast.GenDecl, ts *ast.TypeSpec) bool {
	return commentGroupHasMarker(gen.Doc) || commentGroupHasMarker(ts.Doc) || commentGroupHasMarker(ts.Comment)
}

func commentGroupHasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.Contains(c.Text, generateMarker) {
			return true
		}
	}
	return false
}

func generateFile(pkg packageContext) ([]byte, error) {
	var b bytes.Buffer

	_, _ = fmt.Fprintln(&b, generatedFileIntro)
	_, _ = fmt.Fprintln(&b)
	_, _ = fmt.Fprintf(&b, "package %s\n\n", pkg.Name)
	_, _ = fmt.Fprintln(&b, "func __resetgenZero[T any](v *T) {")
	_, _ = fmt.Fprintln(&b, "\tvar zero T")
	_, _ = fmt.Fprintln(&b, "\t*v = zero")
	_, _ = fmt.Fprintln(&b, "}")
	_, _ = fmt.Fprintln(&b)

	for i, ms := range pkg.MarkedTypes {
		if i > 0 {
			_, _ = fmt.Fprintln(&b)
		}

		_, _ = fmt.Fprintf(&b, "func (r *%s) Reset() {\n", ms.Name)
		_, _ = fmt.Fprintln(&b, "\tif r == nil {")
		_, _ = fmt.Fprintln(&b, "\t\treturn")
		_, _ = fmt.Fprintln(&b, "\t}")
		if ms.Struct.Fields != nil {
			for _, f := range ms.Struct.Fields.List {
				fieldNames := fieldNames(f)
				for _, name := range fieldNames {
					emitResetForType(&b, "\t", "r."+name, "&r."+name, f.Type, pkg.TypeByName, nil)
				}
			}
		}
		_, _ = fmt.Fprintln(&b, "}")
	}

	return b.Bytes(), nil
}

func emitResetForType(b *bytes.Buffer, indent, expr, addrExpr string, typ ast.Expr, typeByName map[string]ast.Expr, seen map[string]bool) {
	resolved := resolveType(typ, typeByName, seen)
	switch t := resolved.(type) {
	case *ast.Ident:
		if isPrimitiveIdent(t.Name) {
			emitZero(b, indent, addrExpr)
			return
		}
		emitResetCallOrZero(b, indent, expr, addrExpr)
	case *ast.ArrayType:
		if t.Len == nil {
			_, _ = fmt.Fprintf(b, "%s%s = %s[:0]\n", indent, expr, expr)
			return
		}
		emitZero(b, indent, addrExpr)
	case *ast.MapType:
		_, _ = fmt.Fprintf(b, "%sclear(%s)\n", indent, expr)
	case *ast.StarExpr:
		_, _ = fmt.Fprintf(b, "%sif %s != nil {\n", indent, expr)
		emitResetForType(b, indent+"\t", derefExpr(expr), expr, t.X, typeByName, seen)
		_, _ = fmt.Fprintf(b, "%s}\n", indent)
	case *ast.StructType:
		emitResetStructOrCall(b, indent, expr, addrExpr, t, typeByName)
	case *ast.InterfaceType, *ast.FuncType, *ast.ChanType:
		emitZero(b, indent, addrExpr)
	default:
		emitResetCallOrZero(b, indent, expr, addrExpr)
	}
}

func emitResetStructOrCall(b *bytes.Buffer, indent, expr, addrExpr string, st *ast.StructType, typeByName map[string]ast.Expr) {
	_, _ = fmt.Fprintf(b, "%sif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", indent, addrExpr)
	_, _ = fmt.Fprintf(b, "%s\tresetter.Reset()\n", indent)
	_, _ = fmt.Fprintf(b, "%s} else {\n", indent)
	if st.Fields != nil {
		for _, f := range st.Fields.List {
			for _, name := range fieldNames(f) {
				fieldExpr := expr + "." + name
				emitResetForType(b, indent+"\t", fieldExpr, "&"+fieldExpr, f.Type, typeByName, nil)
			}
		}
	}
	_, _ = fmt.Fprintf(b, "%s}\n", indent)
}

func emitResetCallOrZero(b *bytes.Buffer, indent, expr, addrExpr string) {
	_, _ = fmt.Fprintf(b, "%sif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", indent, addrExpr)
	_, _ = fmt.Fprintf(b, "%s\tresetter.Reset()\n", indent)
	_, _ = fmt.Fprintf(b, "%s} else {\n", indent)
	emitZero(b, indent+"\t", addrExpr)
	_, _ = fmt.Fprintf(b, "%s}\n", indent)
}

func emitZero(b *bytes.Buffer, indent, addrExpr string) {
	_, _ = fmt.Fprintf(b, "%s__resetgenZero(%s)\n", indent, addrExpr)
}

func resolveType(typ ast.Expr, typeByName map[string]ast.Expr, seen map[string]bool) ast.Expr {
	ident, ok := typ.(*ast.Ident)
	if !ok {
		return typ
	}
	if isPrimitiveIdent(ident.Name) {
		return typ
	}

	target, ok := typeByName[ident.Name]
	if !ok {
		return typ
	}
	if seen == nil {
		seen = make(map[string]bool)
	}
	if seen[ident.Name] {
		return typ
	}
	seen[ident.Name] = true
	defer delete(seen, ident.Name)

	return resolveType(target, typeByName, seen)
}

func fieldNames(f *ast.Field) []string {
	if len(f.Names) > 0 {
		out := make([]string, 0, len(f.Names))
		for _, n := range f.Names {
			out = append(out, n.Name)
		}
		return out
	}
	name := embeddedFieldName(f.Type)
	if name == "" {
		return nil
	}
	return []string{name}
}

func embeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return embeddedFieldName(t.X)
	case *ast.IndexExpr:
		return embeddedFieldName(t.X)
	case *ast.IndexListExpr:
		return embeddedFieldName(t.X)
	default:
		return ""
	}
}

func derefExpr(expr string) string {
	return "(*" + expr + ")"
}

func isPrimitiveIdent(name string) bool {
	switch name {
	case "bool", "string",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return true
	default:
		return false
	}
}

func writeFileIfChanged(path string, content []byte) error {
	old, err := os.ReadFile(path)
	if err == nil && bytes.Equal(old, content) {
		return nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), "resetgen-*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()

	defer func() {
		_ = os.Remove(tmpPath)
	}()

	if _, err := tmp.Write(content); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	return os.Rename(tmpPath, path)
}
