// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/shortener.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
)

const _ = proto.ProtoPackageIsVersion4

var _ = fmt.Errorf

// ListUserURLsRequest contains optional filters for user URL listing.
type ListUserURLsRequest struct{}

func (m *ListUserURLsRequest) Reset()         { *m = ListUserURLsRequest{} }
func (m *ListUserURLsRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserURLsRequest) ProtoMessage()    {}

// URLShortenRequest contains original URL.
type URLShortenRequest struct {
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (m *URLShortenRequest) Reset()         { *m = URLShortenRequest{} }
func (m *URLShortenRequest) String() string { return proto.CompactTextString(m) }
func (*URLShortenRequest) ProtoMessage()    {}

func (m *URLShortenRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}

	return ""
}

// URLShortenResponse contains shortened URL.
type URLShortenResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *URLShortenResponse) Reset()         { *m = URLShortenResponse{} }
func (m *URLShortenResponse) String() string { return proto.CompactTextString(m) }
func (*URLShortenResponse) ProtoMessage()    {}

func (m *URLShortenResponse) GetResult() string {
	if m != nil {
		return m.Result
	}

	return ""
}

// URLExpandRequest contains short id.
type URLExpandRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *URLExpandRequest) Reset()         { *m = URLExpandRequest{} }
func (m *URLExpandRequest) String() string { return proto.CompactTextString(m) }
func (*URLExpandRequest) ProtoMessage()    {}

func (m *URLExpandRequest) GetId() string {
	if m != nil {
		return m.Id
	}

	return ""
}

// URLExpandResponse contains original URL.
type URLExpandResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *URLExpandResponse) Reset()         { *m = URLExpandResponse{} }
func (m *URLExpandResponse) String() string { return proto.CompactTextString(m) }
func (*URLExpandResponse) ProtoMessage()    {}

func (m *URLExpandResponse) GetResult() string {
	if m != nil {
		return m.Result
	}

	return ""
}

// UserURLsResponse contains user URLs.
type UserURLsResponse struct {
	Url []*URLData `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
}

func (m *UserURLsResponse) Reset()         { *m = UserURLsResponse{} }
func (m *UserURLsResponse) String() string { return proto.CompactTextString(m) }
func (*UserURLsResponse) ProtoMessage()    {}

func (m *UserURLsResponse) GetUrl() []*URLData {
	if m != nil {
		return m.Url
	}

	return nil
}

// URLData describes one user URL pair.
type URLData struct {
	ShortUrl    string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (m *URLData) Reset()         { *m = URLData{} }
func (m *URLData) String() string { return proto.CompactTextString(m) }
func (*URLData) ProtoMessage()    {}

func (m *URLData) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}

	return ""
}

func (m *URLData) GetOriginalUrl() string {
	if m != nil {
		return m.OriginalUrl
	}

	return ""
}
